application:
  name: dev-note
  ver: 0.1

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/dev_note?autoReconnect=true&useUnicode=true&zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8
    username: dev_note
    password: dev_note1234
    hikari:
      maximum-pool-size: 5
      idle-timeout: 30000