application:
  name: dev-note
  ver: 0.1

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  info :
    title: dev-note
    description: 개발 기록용 서버
    version: 1.0.0

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/dev_note?autoReconnect=true&useUnicode=true&zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8
    username: dev_note
    password: dev_note1234
    hikari:
      maximum-pool-size: 5
      idle-timeout: 30000